# Generated by Django 6.0.2 on 2026-02-27 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_staff_user_is_admin_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('Project Manager', 'Project Manager'), ('Developer', 'Developer'), ('Tester', 'Tester'), ('User', 'User')], max_length=100),
        ),
    ]
