# Generated by Django 6.0.2 on 2026-03-07 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usertable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('Name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'usertable',
            },
        ),
    ]
