# Generated by Django 6.0.2 on 2026-03-07 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='projectTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('creatd_at', models.DateTimeField()),
                ('status', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BugTracking.usertable')),
            ],
            options={
                'db_table': 'projectTable',
            },
        ),
    ]
