# Generated by Django 6.0.2 on 2026-03-07 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracking', '0002_projecttable'),
    ]

    operations = [
        migrations.CreateModel(
            name='moduletable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_id', models.IntegerField()),
                ('module_name', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BugTracking.projecttable')),
            ],
            options={
                'db_table': 'moduletable',
            },
        ),
    ]
