# Generated by Django 6.0.2 on 2026-03-07 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracking', '0003_moduletable'),
    ]

    operations = [
        migrations.CreateModel(
            name='tasktable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField()),
                ('task_description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(max_length=100)),
                ('assgined_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_assigned_by', to='BugTracking.usertable')),
                ('assgined_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_assigned_to', to='BugTracking.usertable')),
                ('module_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BugTracking.moduletable')),
            ],
            options={
                'db_table': 'tasktable',
            },
        ),
    ]
