# Generated by Django 6.0.2 on 2026-03-07 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracking', '0004_tasktable'),
    ]

    operations = [
        migrations.CreateModel(
            name='bugtrackingtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_id', models.IntegerField()),
                ('Description', models.TextField()),
                ('severity', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('reported_date', models.DateTimeField()),
                ('fix_date', models.DateTimeField()),
                ('assgined_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bug_assgined_to', to='BugTracking.usertable')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bug_reported_by', to='BugTracking.usertable')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BugTracking.tasktable')),
            ],
            options={
                'db_table': 'bugtrackingtable',
            },
        ),
    ]
