# Generated by Django 6.0.2 on 2026-03-07 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracking', '0005_bugtrackingtable'),
    ]

    operations = [
        migrations.CreateModel(
            name='task_time_tracking_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recode_id', models.IntegerField()),
                ('total_time', models.FloatField()),
                ('updated_at', models.DateTimeField()),
                ('Developer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Devaloper_id', to='BugTracking.usertable')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_id', to='BugTracking.usertable')),
            ],
            options={
                'db_table': 'task_time_tracking_table',
            },
        ),
    ]
