# Generated by Django 6.0.2 on 2026-03-07 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracking', '0006_task_time_tracking_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='commentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentd', models.TextField()),
                ('commentd_at', models.DateTimeField()),
                ('bug_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BugTracking.bugtrackingtable')),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BugTracking.usertable')),
            ],
            options={
                'db_table': 'commentTable',
            },
        ),
    ]
