# Generated by Django 6.0.2 on 2026-03-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracking', '0007_commenttable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttable',
            name='creatd_at',
        ),
        migrations.AddField(
            model_name='projecttable',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='projecttable',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
