# Generated by Django 6.0.2 on 2026-03-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracking', '0008_remove_projecttable_creatd_at_projecttable_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttable',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='projecttable',
            name='start_date',
            field=models.DateField(),
        ),
    ]
