# Generated by Django 6.0.2 on 2026-03-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracking', '0009_alter_projecttable_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttable',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='projecttable',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
