# Generated by Django 6.0.2 on 2026-03-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracking', '0011_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='project',
        ),
        migrations.AlterField(
            model_name='usertable',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('Project Manager', 'Project Manager'), ('Developer', 'Developer'), ('Tester', 'Tester')], max_length=100),
        ),
    ]
