# Generated by Django 6.0.2 on 2026-03-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracking', '0012_delete_project_alter_usertable_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='user_id',
            field=models.CharField(max_length=100),
        ),
    ]
