# Generated by Django 6.0.2 on 2026-03-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracking', '0013_alter_usertable_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduletable',
            name='module_id',
            field=models.CharField(max_length=100),
        ),
    ]
