# Generated by Django 6.0.2 on 2026-03-10 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracking', '0014_alter_moduletable_module_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasktable',
            name='assgined_by',
        ),
        migrations.RemoveField(
            model_name='tasktable',
            name='assgined_to',
        ),
    ]
