# Generated by Django 6.0.2 on 2026-03-10 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracking', '0015_remove_tasktable_assgined_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktable',
            name='task_id',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='assginedtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assgined_id', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('assgined_date', models.DateField()),
                ('assgined_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_by', to='BugTracking.usertable')),
                ('assgined_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to', to='BugTracking.usertable')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BugTracking.tasktable')),
            ],
            options={
                'db_table': 'assginedtable',
            },
        ),
    ]
