# Generated by Django 6.0.2 on 2026-03-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracking', '0016_alter_tasktable_task_id_assginedtable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bugtrackingtable',
            name='bug_id',
        ),
        migrations.AlterField(
            model_name='bugtrackingtable',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=100),
        ),
        migrations.AlterField(
            model_name='bugtrackingtable',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed')], max_length=100),
        ),
    ]
