# Generated by Django 6.0.2 on 2026-03-11 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracking', '0017_remove_bugtrackingtable_bug_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assginedtable',
            name='assgined_id',
        ),
    ]
