# Generated by Django 6.0.2 on 2026-03-11 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracking', '0018_remove_assginedtable_assgined_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='assigned_bugtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descriptions', models.TextField()),
                ('assgined_date', models.DateField()),
                ('servity', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], max_length=100)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed')], max_length=100)),
                ('fix_date', models.DateField()),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bug_assigned_to', to='BugTracking.usertable')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bug_related_by', to='BugTracking.usertable')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BugTracking.tasktable')),
            ],
            options={
                'db_table': 'assigned_bugtable',
            },
        ),
    ]
