# Generated by Django 6.0.2 on 2026-03-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracking', '0019_assigned_bugtable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigned_bugtable',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('in_progress', 'In Progress'), ('closed', 'Closed'), ('testing', 'testing'), ('completed', 'completed')], max_length=100),
        ),
    ]
