# Generated by Django 6.0.2 on 2026-03-19 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracking', '0020_alter_assigned_bugtable_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assigned_bugtable',
            old_name='assgined_date',
            new_name='assigned_date',
        ),
        migrations.RenameField(
            model_name='assigned_bugtable',
            old_name='servity',
            new_name='severity',
        ),
    ]
