# Generated by Django 6.0.2 on 2026-03-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracking', '0021_rename_assgined_date_assigned_bugtable_assigned_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigned_bugtable',
            name='assigned_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
