# Generated by Django 6.0.2 on 2026-03-19 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracking', '0022_alter_assigned_bugtable_assigned_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assigned_bugtable',
            name='task_id',
        ),
        migrations.AddField(
            model_name='assigned_bugtable',
            name='bug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bug', to='BugTracking.bugtrackingtable'),
        ),
        migrations.AddField(
            model_name='assigned_bugtable',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='BugTracking.tasktable'),
        ),
    ]
