# Generated by Django 6.0.2 on 2026-03-19 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracking', '0023_remove_assigned_bugtable_task_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigned_bugtable',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_by_form_tester', to='BugTracking.usertable'),
        ),
    ]
