# Generated by Django 6.0.2 on 2026-03-19 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracking', '0024_assigned_bugtable_assigned_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assigned_bugtable',
            old_name='Descriptions',
            new_name='Description',
        ),
    ]
