# Generated by Django 6.0.2 on 2026-03-20 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracking', '0025_rename_descriptions_assigned_bugtable_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='commenttable',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BugTracking.usertable'),
        ),
        migrations.AlterField(
            model_name='commenttable',
            name='bug_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BugTracking.bugtrackingtable'),
        ),
        migrations.AlterField(
            model_name='commenttable',
            name='comment_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commenttable',
            name='commentd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commenttable',
            name='commentd_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
