# Generated by Django 6.0.2 on 2026-03-20 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracking', '0026_commenttable_user_id_alter_commenttable_bug_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigned_bugtable',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bug_related_by', to='BugTracking.usertable'),
        ),
    ]
