# Generated by Django 6.0.2 on 2026-03-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracking', '0027_alter_assigned_bugtable_reported_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigned_bugtable',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
