# Generated by Django 6.0.2 on 2026-03-20 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracking', '0028_assigned_bugtable_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assigned_bugtable',
            name='created_at',
        ),
    ]
