# Generated by Django 6.0.2 on 2026-03-20 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracking', '0029_remove_assigned_bugtable_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertable',
            old_name='Email',
            new_name='email',
        ),
    ]
