# Generated by Django 6.0.2 on 2026-03-21 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracking', '0030_rename_email_usertable_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertable',
            old_name='email',
            new_name='Email',
        ),
    ]
