# Generated by Django 6.0.2 on 2026-04-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracking', '0032_rename_email_usertable_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commenttable',
            name='comment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
