# Generated by Django 6.0.2 on 2026-04-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracking', '0033_alter_commenttable_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttable',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=100),
        ),
    ]
