# Generated by Django 6.0.2 on 2026-04-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracking', '0034_alter_projecttable_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktable',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=100),
        ),
    ]
