# Generated by Django 6.0.2 on 2026-04-10 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracking', '0035_alter_tasktable_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='assginedtable',
            new_name='assignedtable',
        ),
        migrations.RenameField(
            model_name='assignedtable',
            old_name='assgined_by',
            new_name='assigned_by',
        ),
        migrations.RenameField(
            model_name='assignedtable',
            old_name='assgined_date',
            new_name='assigned_date',
        ),
        migrations.RenameField(
            model_name='assignedtable',
            old_name='assgined_to',
            new_name='assigned_to',
        ),
        migrations.RenameField(
            model_name='bugtrackingtable',
            old_name='assgined_to',
            new_name='assigned_to',
        ),
        migrations.AlterModelTable(
            name='assignedtable',
            table='assignedtable',
        ),
    ]
