# Generated by Django 6.0.2 on 2026-04-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracking', '0036_rename_assginedtable_assignedtable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='user_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
