# Generated by Django 6.0.2 on 2026-04-18 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracking', '0037_alter_usertable_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commenttable',
            name='comment_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='projecttable',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BugTracking.usertable'),
        ),
    ]
